# Generated by Django 3.1.7 on 2021-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_num', models.IntegerField(unique=True)),
                ('attrition_flag', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('dependent_count', models.IntegerField()),
                ('education_level', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=10)),
                ('income_category', models.CharField(max_length=50)),
                ('card_category', models.CharField(max_length=10)),
                ('months_on_book', models.IntegerField()),
                ('relation_count', models.IntegerField()),
                ('months_inactive', models.IntegerField()),
                ('contacts_count', models.IntegerField()),
                ('credit_limit', models.FloatField()),
                ('revolving_bal', models.FloatField()),
                ('avg_open_to_buy', models.FloatField()),
                ('amt_chg', models.FloatField()),
                ('trans_amt', models.FloatField()),
                ('trans_ct', models.FloatField()),
                ('ct_change', models.FloatField()),
                ('avg_utilization_ratio', models.FloatField()),
                ('naive_bayes_1', models.FloatField()),
                ('naive_bayes_2', models.FloatField()),
            ],
        ),
    ]
