# Generated by Django 3.1.7 on 2021-03-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20210303_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='client_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='naive_bayes_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='naive_bayes_2',
            field=models.FloatField(),
        ),
    ]
